# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(unique=True)),
                ('cas_id', models.TextField(unique=True)),
                ('description', models.TextField(null=True)),
                ('password', models.TextField()),
                ('first_name', models.TextField(null=True)),
                ('last_name', models.TextField(null=True)),
                ('middle_name', models.TextField(null=True)),
                ('created_at', models.DateTimeField()),
                ('cupdated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='ProfileRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('cupdated_at', models.DateTimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_app.Profile')),
            ],
            options={
                'db_table': 'profile_role',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('from_cas', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('cupdated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.AddField(
            model_name='profilerole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_app.Role'),
        ),
        migrations.AlterUniqueTogether(
            name='profilerole',
            unique_together=set([('profile', 'role')]),
        ),
    ]
