# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0002_auto_20161105_0241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cupdated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='profilerole',
            old_name='cupdated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='cupdated_at',
            new_name='updated_at',
        ),
    ]
